---
# tasks file for win_ad_install
- name: install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: setup AD controller
  win_domain: 
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"

- name: reboot window
  win_reboot: 

- name: print domain list
  win_command: nltest /dclist:"{{ ad_domain_name }}"
  register: domain_list

- debug:
    var: domain_list

  
